# Generated by Django 4.0 on 2021-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver', '0002_alter_driver_first_name_alter_driver_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
