# Generated by Django 4.0 on 2021-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver', '0003_alter_driver_created_at_alter_driver_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
