# Generated by Django 4.0 on 2021-12-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_driver', '0006_alter_driver_created_at_alter_driver_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateField(blank=True),
        ),
    ]
